import { describe, expect, it } from "vitest";
import { parseDanmakuXml, renderDanmakuXml, escapeXmlText } from "../src/extras/danmaku-xml.js";
import { danmakuToAss, measureTextWidth } from "../src/extras/danmaku-ass.js";
import { danmakuToJson } from "../src/extras/danmaku-json.js";
import type { DanmakuEntry } from "../src/extras/types.js";

/** B 站标准弹幕 XML fixture（ASCII 内容，字段来自真实接口样例） */
const SAMPLE_XML = `<?xml version="1.0" encoding="UTF-8"?>
<i><chatserver>chat.bilibili.com</chatserver><chatid>12345</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.60100,4,25,16777215,1604742895,0,9e5adeaa,40685126698926083,10">hello world</d><d p="6.99600,1,25,16711680,1604742895,0,362b0ee5,31039004496363523,9">second line</d><d p="95.45300,5,25,16777215,1604742895,0,14f71d3,44164288244350983,10">top text</d></i>`;

const EXPECTED_ENTRIES: DanmakuEntry[] = [
  { stime: 601, mode: 4, size: 25, color: 16777215, date: 1604742895, uhash: "9e5adeaa", dmid: "40685126698926083", text: "hello world", weight: 10 },
  { stime: 6996, mode: 1, size: 25, color: 16711680, date: 1604742895, uhash: "362b0ee5", dmid: "31039004496363523", text: "second line", weight: 9 },
  { stime: 95453, mode: 5, size: 25, color: 16777215, date: 1604742895, uhash: "14f71d3", dmid: "44164288244350983", text: "top text", weight: 10 },
];

describe("danmaku-xml", () => {
  it("parseDanmakuXml 解析 p 属性与文本（stime 毫秒化）", () => {
    expect(parseDanmakuXml(SAMPLE_XML)).toEqual(EXPECTED_ENTRIES);
  });

  it("parseDanmakuXml 处理 XML 实体与控制字符", () => {
    const xml = `<i><d p="1.00000,1,25,16777215,0,0,a,1">a &amp; b &lt;c&gt;</d><d p="2.00000,1,25,16777215,0,0,b,2">line</d></i>`;
    const entries = parseDanmakuXml(xml);
    expect(entries[0]?.text).toBe("a & b <c>");
    expect(entries).toHaveLength(2);
  });

  it("parseDanmakuXml 丢弃无 stime/无文本条目", () => {
    const xml = `<i><d p="0.00000,1,25,16777215,0,0,a,1">zero time</d><d p="1.00000,1,25,16777215,0,0,b,2"></d><d p="2.00000,1,25,16777215,0,0,c,3">ok</d></i>`;
    const entries = parseDanmakuXml(xml);
    expect(entries.map((e) => e.text)).toEqual(["ok"]);
  });

  it("renderDanmakuXml 生成上游模板结构（秒 5 位小数、8 字段 p、cid 进 chatid）", () => {
    const out = renderDanmakuXml(EXPECTED_ENTRIES, 12345);
    expect(out).toContain("<chatid>12345</chatid>");
    expect(out).toContain("<maxlimit>1500</maxlimit>");
    expect(out).toContain(`<d p="0.60100,4,25,16777215,1604742895,0,9e5adeaa,40685126698926083">hello world</d>`);
    expect(out).toContain(`<d p="6.99600,1,25,16711680,1604742895,0,362b0ee5,31039004496363523">second line</d>`);
    expect(out).toContain(`<d p="95.45300,5,25,16777215,1604742895,0,14f71d3,44164288244350983">top text</d>`);
  });

  it("renderDanmakuXml 转义特殊字符", () => {
    const entries: DanmakuEntry[] = [{ stime: 1000, mode: 1, size: 25, color: 16777215, date: 0, uhash: "a", dmid: "1", text: 'a<b>&"c' }];
    const out = renderDanmakuXml(entries, 1);
    expect(out).toContain("a&lt;b&gt;&amp;&quot;c");
    expect(escapeXmlText("a\u0000b\u0001c&<>\"'")).toBe("abc&amp;&lt;&gt;&quot;&apos;");
  });
});

describe("danmaku-ass", () => {
  it("measureTextWidth：中文全角/ASCII 半角估算", () => {
    expect(measureTextWidth("abc", 36)).toBe(54); // 3 * 18
    expect(measureTextWidth("中文", 36)).toBe(72); // 2 * 36
  });

  it("danmakuToAss：样式行默认值与透明度", () => {
    const out = danmakuToAss([], "Test");
    expect(out.startsWith("[Script Info]\n; Script generated by Bili23 Downloader\n; http://bili23.scott-sloan.cn\nTitle: Test\nScriptType: v4.00+\nWrapStyle: 2\nCollisions: Normal\nScaledBorderAndShadow: yes\nAspect Ratio: 1280:720\nYCbCr Matrix: TV.601\nPlayResX: 1280\nPlayResY: 720\n")).toBe(true);
    // opacity 80 → alpha 51=0x33；描边 1.0、阴影 0
    expect(out).toContain(
      "Style: Default,黑体,36,&H32FFFFFF,&H320000FF,&H32000000,&H32000000,0,0,0,0,100,100,0,0,1,1.0,0,7,0,0,0,1",
    );
    expect(out).toContain("[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n");
  });

  it("danmakuToAss：滚动弹幕 → \\move；底部/顶部 → pos", () => {
    const entries: DanmakuEntry[] = [
      { stime: 601, mode: 4, size: 25, color: 16777215, date: 0, uhash: "a", dmid: "1", text: "hello world" },
      { stime: 6996, mode: 1, size: 25, color: 16711680, date: 0, uhash: "b", dmid: "2", text: "second line" },
      { stime: 95453, mode: 5, size: 25, color: 16777215, date: 0, uhash: "c", dmid: "3", text: "top text" },
    ];
    const out = danmakuToAss(entries, "Sample");
    // 底部弹幕（模式 4）：an2 pos 底部；白色不附颜色标签
    expect(out).toContain("Dialogue: 0,0:00:00.60,0:00:05.60,Default,,0,0,0,,{\\an2\\pos(640,720)}hello world");
    // 滚动弹幕（模式 1）：move；彩色弹幕附 \c&H BGR
    expect(out).toContain("Dialogue: 0,0:00:06.99,0:00:16.99,Default,,0,0,0,,{\\move(1280,0,-198,0)\\c&H0000FF&}second line");
    // 顶部弹幕（模式 5）：an8 pos 顶部
    expect(out).toContain("Dialogue: 0,0:01:35.45,0:01:40.45,Default,,0,0,0,,{\\an8\\pos(640,0)}top text");
  });

  it("danmakuToAss：满屏时丢弃无法分配的弹幕（不抛错）", () => {
    // 同一时刻同一轨道大量弹幕，后到者应被丢弃或分流，但输出仍为合法 ASS
    const entries: DanmakuEntry[] = Array.from({ length: 50 }, (_, i) => ({
      stime: 1000 + i,
      mode: 1,
      size: 25,
      color: 16777215,
      date: 0,
      uhash: "a",
      dmid: String(i),
      text: "fill",
    }));
    const out = danmakuToAss(entries, "Sample");
    expect(out.startsWith("[Script Info]")).toBe(true);
    expect(out).toContain("[Events]");
  });
});

describe("danmaku-json", () => {
  it("danmakuToJson 输出条目数组 indent=2", () => {
    const entries = [EXPECTED_ENTRIES[0] as DanmakuEntry, EXPECTED_ENTRIES[1] as DanmakuEntry];
    const out = danmakuToJson(entries);
    expect(JSON.parse(out)).toEqual(entries);
    expect(out).toContain("\n  ");
  });
});
