/**
 * ASS 文档骨架（弹幕/字幕 ASS 共用）。
 * 模板逐字对齐桌面 file/danmaku_ass.py 与 file/subtitle_ass.py 的 ass_base。
 */

export interface AssRenderInput {
  title: string;
  styleLine: string;
  dialogues: string[];
  width: number;
  height: number;
}

export const ASS_SCRIPT_INFO_HEADER = `[Script Info]
; Script generated by Bili23 Downloader
; http://bili23.scott-sloan.cn`;

export function renderAss(input: AssRenderInput): string {
  const { title, styleLine, dialogues, width, height } = input;
  return `${ASS_SCRIPT_INFO_HEADER}
Title: ${title}
ScriptType: v4.00+
WrapStyle: 2
Collisions: Normal
ScaledBorderAndShadow: yes
Aspect Ratio: ${width}:${height}
YCbCr Matrix: TV.601
PlayResX: ${width}
PlayResY: ${height}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
${styleLine}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
${dialogues.join("\n")}
`;
}
